### ISSUE TITLE
roxmltree v0.11.1 breaks code that worked with v0.11.0

### ISSUE THREAD

**Issue by psychon** [RazrFalcon/roxmltree#36]
Hi,

you broke my build. ;-)

This is just a FYI that something happened. I guess that nothing can be done about it even though v0.11.1 is not semver compatible with v0.11.0 (or I misunderstood something).

The error is:
```
error[E0621]: explicit lifetime required in the type of `name`
    --> xcbgen-rs/src/parser.rs:1129:5
     |
1128 | fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &str) -> Result<&'a str, ParseError> {
     |                                                      ---- help: add explicit lifetime `'a` to the type of `name`: `&'a str`
1129 |     node.attribute(name).ok_or(ParseError::InvalidXml)
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'a` required
error: aborting due to previous error
```
The code in question is this:
https://github.com/psychon/x11rb/blob/7f2407f735881acebb46c93eb3bc8fed3fa99814/xcbgen-rs/src/parser.rs#L1128-L1130
```rust
fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &str) -> Result<&'a str, ParseError> {
    node.attribute(name).ok_or(ParseError::InvalidXml)
}
```
I haven't looked closely yet at what happened, but the compiler's suggestion seems wrong to me. Perhaps I need `Node<'a, 'a>`? Dunno, future-me will experiment with this.

Anyway, feel free to just close this issue. As I said, I just wanted to let you know about this.

**Comment by RazrFalcon** [comment]
Yes, I guess 0.11.1 should be yanked and replaced with 0.12. Looks like the last change was actually a breaking one.

As for the fix, the method should look like this:

https://github.com/RazrFalcon/roxmltree/blob/b358cce15ab0663909659f2822ac2c9f6a7d7c9e/tests/api.rs#L269

**Comment by RazrFalcon** [comment]
Done.

**Comment by psychon** [comment]
Thanks for the fix

**Comment by psychon** [comment]
However, it didn't actually help me. Sorry.

`attribute()` returns an `Option<&'a str>`, so adding an `'input` lifetime does not help here. Instead, I have to ensure that the given `&str` lives for `'a`, i.e.:
```diff
diff --git a/xcbgen-rs/src/parser.rs b/xcbgen-rs/src/parser.rs
index a3a4d39..082ad39 100644
--- a/xcbgen-rs/src/parser.rs
+++ b/xcbgen-rs/src/parser.rs
@@ -1125,7 +1125,7 @@ impl Parser {
     }
 }
 
-fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &str) -> Result<&'a str, ParseError> {
+fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &'a str) -> Result<&'a str, ParseError> {
     node.attribute(name).ok_or(ParseError::InvalidXml)
 }
 
```
Since the `&str` used in my code are all `'static`, this works for me, but I do not think that this is intended in roxmltree. The implementation certainly does not keep the given `name` around / borrows it in its result.

Put differenly, the `'n` here is not really used:
https://github.com/RazrFalcon/roxmltree/blob/a419321475a2936a4bf8da3c2f0ce9de3a0d62e2/src/lib.rs#L915-L917
...because this code requires the given string to live for `'input` and not for `'n` (aka `'a` in the code below):
https://github.com/RazrFalcon/roxmltree/blob/a419321475a2936a4bf8da3c2f0ce9de3a0d62e2/src/lib.rs#L642-L650

**Comment by RazrFalcon** [comment]
Well, it was an intended breaking change.

As for the lifetimes, I'm not good with them either. Personally, I'm not using roxmltree in that way, so I do not encountering such problems.

The latest change should be correct, afaik. Therefore we should figure out how to fix your code.

This version works for me:

```
fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &'a str) -> Result<&'a str, ParseError> {
```

**Comment by psychon** [comment]
Thanks for bearing with me. Perhaps to make it a bit clearer what I mean with the lifetimes above (which I never said clearly, so new attempt: "I think your lifetimes requirements are too strict"):
```diff
diff --git a/src/lib.rs b/src/lib.rs
index 8e693d0..eda61dd 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -912,9 +912,9 @@ impl<'a, 'input: 'a> Node<'a, 'input> {
     /// assert_eq!(doc.root_element().attribute("a"), Some("b"));
     /// assert_eq!(doc.root_element().attribute(("http://www.w3.org", "a")), Some("c"));
     /// ```
-    pub fn attribute<'n, N>(&self, name: N) -> Option<&'a str>
+    pub fn attribute<'n, 'm, N>(&self, name: N) -> Option<&'a str>
     where
-        N: Into<ExpandedName<'n, 'input>>,
+        N: Into<ExpandedName<'n, 'm>>,
     {
         let name = name.into();
         self.attributes().iter().find(|a| a.name.as_ref() == name).map(|a| a.value.as_ref())
diff --git a/tests/api.rs b/tests/api.rs
index bc65b56..6284bcb 100644
--- a/tests/api.rs
+++ b/tests/api.rs
@@ -275,3 +275,22 @@ fn tag_name_lifetime() {
     let root = doc.root_element();
     assert_eq!(get_tag_name(&root), "e");
 }
+
+#[test]
+fn this_is_basically_a_compile_test() {
+    let data = "<e xmlns='http://www.w3.org' />";
+    let doc = roxmltree::Document::parse(data).unwrap();
+    let root = doc.root_element();
+    let attribute = {
+        // Get a &str with a shorter lifetime than the document
+        let attr = "whatever".to_string();
+        let attr = &*attr;
+        root.attribute(attr)
+    };
+    assert_eq!(attribute, None);
+}
+
+// This is just here to see if it compiles
+fn get_attr<'a>(node: roxmltree::Node<'a, '_>, name: &str) -> Result<&'a str, ()> {
+    node.attribute(name).ok_or(())
+}
```
Neither the function `get_attr` nor the new "test" compile without the changes to `lib.rs`. This `get_attr` is just the old version of the `get_attr` function that is currently used in x11rb. I will not submit a PR, because that would require doing this properly, which means to actually check all the uses of `ExpandedName` for possibly too strict lifetimes. I just wanted to know about this finding.

> PS: from my experience, passing &Node is easier then a copy. It makes compiler's life easier.

Yup. I am not sure what is up with the code in x11rb here and it definitely makes no sense to copy the node here.

**Comment by RazrFalcon** [comment]
Honestly, I have no idea how exactly it should be implemented. I don't like investigating lifetime bugs. The current code works fine for my use case and that's all I care about. If you think you can improve it, then please send a PR with corresponding tests. Until then, I will leave everything as is.
